name: OpenScenarioCppArtifacts
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Artifacts name'
        default: 'OpenScenarioCppArtifacts'


jobs:
  # Linux shared
  LinuxSharedDebugBuild:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: update system
      run:  sudo apt-get update

    - name: install uuid-dev package
      run:  sudo apt-get install uuid-dev
    
    - name: cmake generate solution Debug
      run: cmake -DCMAKE_BUILD_TYPE="Debug" -DBUILD_STATIC_LIBS="OFF" -DPLATFORM_PARAM="Linux" ./cpp
      
    - name: build solution Debug
      run: make
    
    - name: publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: LinuxSharedDebug
        path: ./cpp/build/output/LinuxShared/Debug/*

#
#  LinuxSharedReleaseBuild:
#    runs-on: ubuntu-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: update system
#      run:  sudo apt-get update
#
#    - name: install uuid-dev package
#      run:  sudo apt-get install uuid-dev
#    
#    - name: cmake generate solution Release
#      run: cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_STATIC_LIBS="OFF" -DPLATFORM_PARAM="Linux" ./cpp
#      
#    - name: build solution Release
#      run: make
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: LinuxSharedRelease
#        path: ./cpp/build/output/LinuxShared/Release/*
#
#
#  # Linux static
#  LinuxStaticDebugBuild:
#    runs-on: ubuntu-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: update system
#      run:  sudo apt-get update
#
#    - name: install uuid-dev package
#      run:  sudo apt-get install uuid-dev
#    
#    - name: cmake generate solution Debug
#      run: cmake -DCMAKE_BUILD_TYPE="Debug" -DBUILD_STATIC_LIBS="ON" -DPLATFORM_PARAM="Linux" ./cpp
#      
#    - name: build solution Debug
#      run: make
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: LinuxStaticDebug
#        path: ./cpp/build/output/LinuxStatic/Debug/*
#
#
#  LinuxStaticReleaseBuild:
#    runs-on: ubuntu-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: update system
#      run:  sudo apt-get update
#
#    - name: install uuid-dev package
#      run:  sudo apt-get install uuid-dev
#    
#    - name: cmake generate solution Release
#      run: cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_STATIC_LIBS="ON" -DPLATFORM_PARAM="Linux" ./cpp
#      
#    - name: build solution Release
#      run: make
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: LinuxStaticRelease
#        path: ./cpp/build/output/LinuxStatic/Release/*
#
#
#  # Win32 shared
#  Win32SharedDebugBuild:
#    runs-on: windows-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    
#    - name: cmake generate solution Debug
#      run: cmake -G "Visual Studio 16 2019" -A Win32 ./cpp -DMASTER_PROJECT=TRUE -DBUILD_STATIC_LIBS="OFF"
#      
#    - name: build solution Debug
#      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe OpenScenario-Cpp.sln /t:Build /p:Configuration=Debug /p:Platform=Win32
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: Win32SharedDebug
#        path: ./cpp/build/output/Win32Shared/Debug/*
#
#
#  Win32SharedReleaseBuild:
#    runs-on: windows-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    
#    - name: cmake generate solution Release
#      run: cmake -G "Visual Studio 16 2019" -A Win32 ./cpp -DMASTER_PROJECT=TRUE -DBUILD_STATIC_LIBS="OFF"
#      
#    - name: build solution Release
#      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe OpenScenario-Cpp.sln /t:Build /p:Configuration=Release /p:Platform=Win32
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: Win32SharedRelease
#        path: ./cpp/build/output/Win32Shared/Release/*
#
#
#  # x64 shared
#  x64SharedDebugBuild:
#    runs-on: windows-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    
#    - name: cmake generate solution Debug
#      run: cmake -G "Visual Studio 16 2019" -A x64 ./cpp -DMASTER_PROJECT=TRUE -DBUILD_STATIC_LIBS="OFF"
#      
#    - name: build solution Debug
#      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe OpenScenario-Cpp.sln /t:Build /p:Configuration=Debug /p:Platform=x64
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: x64SharedDebug
#        path: ./cpp/build/output/x64Shared/Debug/*
#
#
#  x64SharedReleaseBuild:
#    runs-on: windows-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    
#    - name: cmake generate solution Release
#      run: cmake -G "Visual Studio 16 2019" -A x64 ./cpp -DMASTER_PROJECT=TRUE -DBUILD_STATIC_LIBS="OFF"
#      
#    - name: build solution Release
#      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe OpenScenario-Cpp.sln /t:Build /p:Configuration=Release /p:Platform=x64
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: x64SharedRelease
#        path: ./cpp/build/output/x64Shared/Release/*
#
#
#  # Win32 static
#  Win32StaticDebugBuild:
#    runs-on: windows-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    
#    - name: cmake generate solution Debug
#      run: cmake -G "Visual Studio 16 2019" -A Win32 ./cpp -DMASTER_PROJECT=TRUE -DBUILD_STATIC_LIBS="ON"
#      
#    - name: build solution Debug
#      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe OpenScenario-Cpp.sln /t:Build /p:Configuration=Debug /p:Platform=Win32
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: Win32StaticDebug
#        path: ./cpp/build/output/Win32Static/Debug/*
#
#
#  Win32StaticReleaseBuild:
#    runs-on: windows-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    
#    - name: cmake generate solution Release
#      run: cmake -G "Visual Studio 16 2019" -A Win32 ./cpp -DMASTER_PROJECT=TRUE -DBUILD_STATIC_LIBS="ON"
#      
#    - name: build solution Release
#      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe OpenScenario-Cpp.sln /t:Build /p:Configuration=Release /p:Platform=Win32
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: Win32StaticRelease
#        path: ./cpp/build/output/Win32Static/Release/*
#
#
#  # x64 static
#  x64StaticDebugBuild:
#    runs-on: windows-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    
#    - name: cmake generate solution Debug
#      run: cmake -G "Visual Studio 16 2019" -A x64 ./cpp -DMASTER_PROJECT=TRUE -DBUILD_STATIC_LIBS="ON"
#      
#    - name: build solution Debug
#      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe OpenScenario-Cpp.sln /t:Build /p:Configuration=Debug /p:Platform=x64
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: x64StaticDebug
#        path: ./cpp/build/output/x64Static/Debug/*
#
#
#  x64StaticReleaseBuild:
#    runs-on: windows-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    
#    - name: cmake generate solution Release
#      run: cmake -G "Visual Studio 16 2019" -A x64 ./cpp -DMASTER_PROJECT=TRUE -DBUILD_STATIC_LIBS="ON"
#      
#    - name: build solution Release
#      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe OpenScenario-Cpp.sln /t:Build /p:Configuration=Release /p:Platform=x64
#    
#    - name: publish artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: x64StaticRelease
#        path: ./cpp/build/output/x64Static/Release/*
#
